# Generated by Django 3.0 on 2019-12-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('main', '0002_game_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='authorization',
            field=models.ManyToManyField(blank=True, to='authtoken.Token'),
        ),
    ]
