# Generated by Django 3.0 on 2019-12-17 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191217_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='active_game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_game', to='main.Game'),
        ),
    ]
