# Generated by Django 3.0 on 2019-12-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191217_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('count', 'game')},
        ),
    ]
