# Generated by Django 3.0 on 2020-01-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('main', '0008_auto_20191219_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='authorization',
            field=models.ManyToManyField(to='authtoken.Token'),
        ),
    ]
