# Generated by Django 3.0 on 2020-01-06 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('main', '0009_auto_20200106_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='authtoken.Token'),
        ),
    ]
