# Generated by Django 3.0 on 2020-01-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200108_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendUser',
        ),
    ]
